### ISSUE TITLE
Error parsing URL with AWS upload provider

### ISSUE THREAD

**Issue by samhenderson511** [emil-petras/strapi-blurhash#19]
I think an update to the strapi upload plugin has broken something here. When I try to upload an image I get this error:

I'm also uploading an SVG which obviously won't work but it used to just get ignored.

```
[2024-04-25 13:46:32.381] http: GET /upload/folders?page=1&sort=createdAt:DESC&pageSize=50&filters[$and][0][parent][id][$null]=true&pagination[pageSize]=-1 (269 ms) 200
[2024-04-25 13:46:38.198] error: Error generating blurhash: Failed to parse URL from http://localhost:1337https://[bucketname].s3.eu-north-1.amazonaws.com/dgk_48510e3136.svg
[2024-04-25 13:46:38.200] error: Failed to parse URL from http://localhost:1337https://[bucketname].s3.eu-north-1.amazonaws.com/dgk_48510e3136.svg
TypeError: Failed to parse URL from http://localhost:1337https://[bucketname].eu-north-1.amazonaws.com/dgk_48510e3136.svg
    at node:internal/deps/undici/undici:12618:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.generateBlurhash (/Users/samhenderson/Development/[projectname]/node_modules/strapi-blurhash/server/services/blurhash.js:7:24)
    at async generateBlurhash (/Users/samhenderson/Development/[projectname]/node_modules/strapi-blurhash/server/bootstrap.js:11:23)
    at async Object.run (/Users/samhenderson/Development/[projectname]/node_modules/@strapi/database/dist/index.js:6029:11)
    at async Object.create (/Users/samhenderson/Development/[projectname]/node_modules/@strapi/database/dist/index.js:5092:22)
    at async Object.add (/Users/samhenderson/Development/[projectname]/node_modules/@strapi/plugin-upload/server/services/upload.js:407:17)
    at async Promise.all (index 0)
    at async Object.upload (/Users/samhenderson/Development/[projectname]/node_modules/@strapi/plugin-upload/server/services/upload.js:210:23)
    at async uploadFiles (/Users/samhenderson/Development/[projectname]/node_modules/@strapi/plugin-upload/server/controllers/admin-upload.js:79:27)
```

**Comment by emil-petras** [comment]
The issue is with the url. I've fixed it in the v1.2.3. Update it and try now.
