### ISSUE TITLE
Could not load the "sharp" module using the win32-x64 runtime ERR_DLOPEN_FAILED: The specified procedure could not be found.

### ISSUE THREAD

**Issue by itsmeJomit** [emil-petras/strapi-blurhash#21]
Error: Could not load js config file C:\laragon\www\cafs\node_modules\strapi-blurhash\strapi-server.js: Could not load the "sharp" module using the win32-x64 runtime
ERR_DLOPEN_FAILED: The specified procedure could not be found.
\\?\C:\laragon\www\cafs\node_modules\@img\sharp-win32-x64\lib\sharp-win32-x64.node
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
    yarn add sharp --ignore-engines
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=win32 --cpu=x64 sharp
- Using the canvas package on Windows?
    See https://sharp.pixelplumbing.com/install#canvas-and-windows
- Check for outdated versions of sharp in the dependency tree:
    npm ls sharp
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    at loadJsFile (C:\laragon\www\cafs\node_modules\@strapi\strapi\lib\core\app-configuration\load-config-file.js:18:11)
    at loadFile (C:\laragon\www\cafs\node_modules\@strapi\strapi\lib\core\app-configuration\load-config-file.js:35:14)
    at Object.loadPlugins (C:\laragon\www\cafs\node_modules\@strapi\strapi\lib\core\loaders\plugins\index.js:103:26)
    at async Strapi.loadPlugins (C:\laragon\www\cafs\node_modules\@strapi\strapi\lib\Strapi.js:352:5)
    at async Promise.all (index 3)
    at async Strapi.register (C:\laragon\www\cafs\node_modules\@strapi\strapi\lib\Strapi.js:392:5)
    at async Strapi.load (C:\laragon\www\cafs\node_modules\@strapi\strapi\lib\Strapi.js:503:5)
    at async workerProcess (C:\laragon\www\cafs\node_modules\@strapi\strapi\lib\commands\actions\develop\action.js:110:26)

**Comment by itsmeJomit** [comment]
this is in a windows system

**Comment by emil-petras** [comment]
I've removed the sharp dependency in the new version. It slower, but it solves the issue.
