### ISSUE TITLE
Error: Cannot read properties of null (reading 'mime'). where from event.params.data is undefined

### ISSUE THREAD

**Issue by tirthbodawala** [emil-petras/strapi-blurhash#7]
Strapi & Strapi Blurhash details:
```
"dependencies": {
    // ...
    "@strapi/strapi": "4.9.0",
    "strapi-blurhash": "^1.1.0",
    // ...
  }
``` 

I am unable to use the plugin and every upload throws an error. seems like event.params.where is undefined. Maybe something changed in strapi which needs to be handled differently. 

```
// event.params.data
{
  name: '1440 - 02@2x.png',
  alternativeText: undefined,
  caption: undefined,
  folder: null,
  folderPath: '/',
  hash: '1440_02_2x_600588b2dc',
  ext: '.png',
  mime: 'image/png',
  size: 51.66,
  tmpWorkingDirectory: '/zb/dm5vv8357gz20k6h0wkl29k80000gn/T/strapi-upload-v5RrQH',
  getStream: [Function (anonymous)],
  width: 2880,
  height: 2048,
  url: '/uploads/1440_02_2x_600588b2dc.png',
  formats: {
    thumbnail: {
      name: 'thumbnail_1440 - 02@2x.png',
      hash: 'thumbnail_1440_02_2x_600588b2dc',
      ext: '.png',
      mime: 'image/png',
      path: null,
      getStream: [Function: getStream],
      width: 219,
      height: 156,
      size: 10.73,
      url: '/uploads/thumbnail_1440_02_2x_600588b2dc.png'
    },
    medium: {
      name: 'medium_1440 - 02@2x.png',
      hash: 'medium_1440_02_2x_600588b2dc',
      ext: '.png',
      mime: 'image/png',
      path: null,
      getStream: [Function: getStream],
      width: 768,
      height: 546,
      size: 52.8,
      url: '/uploads/medium_1440_02_2x_600588b2dc.png'
    },
    small: {
      name: 'small_1440 - 02@2x.png',
      hash: 'small_1440_02_2x_600588b2dc',
      ext: '.png',
      mime: 'image/png',
      path: null,
      getStream: [Function: getStream],
      width: 576,
      height: 410,
      size: 36.44,
      url: '/uploads/small_1440_02_2x_600588b2dc.png'
    },
    large: {
      name: 'large_1440 - 02@2x.png',
      hash: 'large_1440_02_2x_600588b2dc',
      ext: '.png',
      mime: 'image/png',
      path: null,
      getStream: [Function: getStream],
      width: 992,
      height: 705,
      size: 74.35,
      url: '/uploads/large_1440_02_2x_600588b2dc.png'
    },
  },
  provider: 'local',
  updatedBy: 1,
  createdBy: 1,
  createdAt: 2023-03-31T09:23:47.249Z,
  updatedAt: 2023-03-31T09:23:47.249Z
}
// event.params.where
undefined

// fullData
fullData::  null

error: Cannot read properties of null (reading 'mime')
TypeError: Cannot read properties of null (reading 'mime')
    at Object.generateBlurhash (<path>/node_modules/strapi-blurhash/server/bootstrap.js:20:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.run (<path>/node_modules/@strapi/database/lib/lifecycles/index.js:76:11)
    at async Object.create (<path>/node_modules/@strapi/database/lib/entity-manager/index.js:213:22)
    at async Object.add (<path>/node_modules/@strapi/plugin-upload/server/services/upload.js:364:17)
    at async Promise.all (index 0)
    at async Object.upload (<path>/node_modules/@strapi/plugin-upload/server/services/upload.js:172:23)
    at async uploadFiles (<path>/node_modules/@strapi/plugin-upload/server/controllers/admin-upload.js:79:27)
    at async Object.upload (<path>/node_modules/@strapi/plugin-upload/server/controllers/admin-upload.js:101:5)
    at async returnBodyMiddleware (<path>/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18
```

Thank you in advance for looking into it :)

**Comment by ThomasValois** [comment]
Took me a while to figure out this issue, ended up looking in my Railway logs. It looks like the upgrade to v1.1.1 has fixed the issue. Interestingly enough was working locally but not in production though.
